// Mocks generated by Mockito 5.4.6 from annotations
// in voiceapp/test/unit/providers/agent_switcher_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:voiceapp/models/conversation_state.dart' as _i4;
import 'package:voiceapp/models/message.dart' as _i5;
import 'package:voiceapp/models/settings.dart' as _i2;
import 'package:voiceapp/providers/conversation_provider.dart' as _i3;
import 'package:voiceapp/services/speech_service.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettings_0 extends _i1.SmartFake implements _i2.Settings {
  _FakeSettings_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [ConversationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationProvider extends _i1.Mock
    implements _i3.ConversationProvider {
  MockConversationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ConversationState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i4.ConversationState.idle,
      ) as _i4.ConversationState);

  @override
  List<_i5.Message> get messages => (super.noSuchMethod(
        Invocation.getter(#messages),
        returnValue: <_i5.Message>[],
      ) as List<_i5.Message>);

  @override
  String get partialSttText => (super.noSuchMethod(
        Invocation.getter(#partialSttText),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#partialSttText),
        ),
      ) as String);

  @override
  _i2.Settings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeSettings_0(this, Invocation.getter(#settings)),
      ) as _i2.Settings);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get hasApiKey =>
      (super.noSuchMethod(Invocation.getter(#hasApiKey), returnValue: false)
          as bool);

  @override
  bool get conversationalMode => (super.noSuchMethod(
        Invocation.getter(#conversationalMode),
        returnValue: false,
      ) as bool);

  @override
  double get pauseDuration =>
      (super.noSuchMethod(Invocation.getter(#pauseDuration), returnValue: 0.0)
          as double);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void forceStateForTesting(_i4.ConversationState? state) => super.noSuchMethod(
        Invocation.method(#forceStateForTesting, [state]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(#initialize, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> initializeForAgent(_i2.Settings? agentSettings) =>
      (super.noSuchMethod(
        Invocation.method(#initializeForAgent, [agentSettings]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void toggleConversation() => super.noSuchMethod(
        Invocation.method(#toggleConversation, []),
        returnValueForMissingStub: null,
      );

  @override
  void clearMessages() => super.noSuchMethod(
        Invocation.method(#clearMessages, []),
        returnValueForMissingStub: null,
      );

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(#clearError, []),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> updateSettings(_i2.Settings? newSettings) =>
      (super.noSuchMethod(
        Invocation.method(#updateSettings, [newSettings]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> applyAgentSettings(_i2.Settings? agentSettings) =>
      (super.noSuchMethod(
        Invocation.method(#applyAgentSettings, [agentSettings]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(#dispose, []),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(#addListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(#removeListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(#notifyListeners, []),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SpeechService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeechService extends _i1.Mock implements _i9.SpeechService {
  MockSpeechService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAvailable =>
      (super.noSuchMethod(Invocation.getter(#isAvailable), returnValue: false)
          as bool);

  @override
  bool get isListening =>
      (super.noSuchMethod(Invocation.getter(#isListening), returnValue: false)
          as bool);

  @override
  bool get hasReportedStopForTesting => (super.noSuchMethod(
        Invocation.getter(#hasReportedStopForTesting),
        returnValue: false,
      ) as bool);

  @override
  set onFinalResult(dynamic Function(String)? value) => super.noSuchMethod(
        Invocation.setter(#onFinalResult, value),
        returnValueForMissingStub: null,
      );

  @override
  set onPartialResult(dynamic Function(String)? value) => super.noSuchMethod(
        Invocation.setter(#onPartialResult, value),
        returnValueForMissingStub: null,
      );

  @override
  set onStopped(dynamic Function()? value) => super.noSuchMethod(
        Invocation.setter(#onStopped, value),
        returnValueForMissingStub: null,
      );

  @override
  void triggerStatusForTesting(String? status) => super.noSuchMethod(
        Invocation.method(#triggerStatusForTesting, [status]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(#initialize, []),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> startListening({
    Duration? pauseDuration = const Duration(seconds: 4),
  }) =>
      (super.noSuchMethod(
        Invocation.method(#startListening, [], {
          #pauseDuration: pauseDuration,
        }),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> stopListening() => (super.noSuchMethod(
        Invocation.method(#stopListening, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cancelListening() => (super.noSuchMethod(
        Invocation.method(#cancelListening, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(#dispose, []),
        returnValueForMissingStub: null,
      );
}
